# Generated by Django 2.2.6 on 2019-10-23 18:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 23, 19, 17, 43, 195997, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='tokens',
            name='token_type',
            field=models.IntegerField(choices=[(0, 'Email Confirmation'), (1, 'Mobile Confirmation'), (2, 'Forgot Password'), (3, 'Login'), (4, 'Order Confirm')], db_index=True, default=0),
        ),
    ]
