# Generated by Django 2.2.6 on 2019-10-26 03:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tokens',
            name='expire_on',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 4, 2, 26, 856102, tzinfo=utc)),
        ),
    ]
