# Generated by Django 2.2.6 on 2019-10-23 18:25

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('merchant_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('merchant_slug', models.SlugField(max_length=255, unique=True)),
                ('merchant_name', models.CharField(db_index=True, max_length=255)),
                ('merchant_contact', models.IntegerField(db_index=True)),
                ('merchant_email', models.EmailField(db_index=True, max_length=254)),
                ('using_our_db', models.BooleanField(db_index=True, default=False, verbose_name='Merchan Using Our DB')),
                ('other_details', models.TextField()),
                ('other', models.CharField(max_length=255)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merchant',
                'verbose_name_plural': 'Merchants',
            },
        ),
        migrations.CreateModel(
            name='MerchantAccessKeys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('secret_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
            },
        ),
        migrations.CreateModel(
            name='MerchantCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('category_slug', models.SlugField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Store Category',
                'verbose_name_plural': 'Store Categories',
            },
        ),
        migrations.CreateModel(
            name='MerchantCoupons',
            fields=[
                ('coupon_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('coupon_code', models.CharField(max_length=50, unique=True)),
                ('min_price_for_discount', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=12)),
                ('max_discount', models.DecimalField(db_index=True, decimal_places=2, default=0.0, max_digits=12, verbose_name='In Flat Rupee')),
                ('discount_type', models.IntegerField(choices=[(1, 'Percent'), (2, 'Flat')], db_index=True, default=1)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('available_after', models.DateTimeField(db_index=True)),
                ('expire_before', models.DateTimeField(db_index=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('discount_by_merchant', models.BooleanField(default=True, verbose_name='Discount Given by Merchant')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Offers',
                'verbose_name_plural': 'Products Offers',
            },
        ),
        migrations.CreateModel(
            name='MerchantEmployees',
            fields=[
                ('emp_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.IntegerField(choices=[(1, 'Manager'), (2, 'Asst. Manager'), (3, 'Salesman'), (4, 'Billing'), (5, 'Other')], db_index=True, default=5)),
                ('other', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merchant User',
                'verbose_name_plural': 'Merchant Users',
            },
        ),
        migrations.CreateModel(
            name='MerchantOffers',
            fields=[
                ('offer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='offers/images/')),
                ('offer_details', models.TextField()),
                ('available_after', models.DateTimeField(db_index=True)),
                ('expire_before', models.DateTimeField(db_index=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merchant Offer',
                'verbose_name_plural': 'Merchant Offers',
            },
        ),
        migrations.CreateModel(
            name='MerchantWebsiteAPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('secret_key', models.CharField(db_index=True, max_length=255, unique=True)),
                ('api_url', models.URLField()),
                ('method', models.IntegerField(choices=[(1, 'GET'), (2, 'POST'), (3, 'PUT'), (4, 'DELETE'), (5, 'PATCH')], db_index=True, default=1)),
                ('api_use', models.IntegerField(choices=[(1, 'PRODUCT'), (2, 'PRODUCTS'), (3, 'PAYMENT')], db_index=True, default=1)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merchants API',
                'verbose_name_plural': 'Merchants API',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('store_latitude', models.CharField(max_length=255)),
                ('store_longitude', models.CharField(max_length=255)),
                ('store_size', models.IntegerField(choices=[(0, 'SMALL'), (1, 'MID'), (2, 'LARGE')], default=0)),
                ('store_map_url', models.URLField()),
                ('store_slug', models.SlugField(max_length=255, unique=True)),
                ('store_name', models.CharField(db_index=True, max_length=255)),
                ('store_contact', models.IntegerField(db_index=True)),
                ('store_email', models.EmailField(db_index=True, max_length=254)),
                ('is_approved', models.BooleanField(db_index=True, default=False)),
                ('provide_delivery', models.BooleanField(db_index=True, default=False)),
                ('min_delivery_payment', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('delivery_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('other', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Merchant Store',
                'verbose_name_plural': 'Merchant Stores',
            },
        ),
    ]
