# Generated by Django 2.2.6 on 2019-10-23 18:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='store',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Merchant'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Addresses'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_category',
            field=models.ManyToManyField(to='merchants.MerchantCategory'),
        ),
        migrations.AddField(
            model_name='store',
            name='store_head',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantwebsiteapi',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='merchants.Merchant'),
        ),
        migrations.AddField(
            model_name='merchantwebsiteapi',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='merchants.Store'),
        ),
        migrations.AddField(
            model_name='merchantoffers',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantoffers',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Merchant'),
        ),
        migrations.AddField(
            model_name='merchantoffers',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Store'),
        ),
        migrations.AddField(
            model_name='merchantemployees',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emp_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantemployees',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Merchant'),
        ),
        migrations.AddField(
            model_name='merchantemployees',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Store'),
        ),
        migrations.AddField(
            model_name='merchantemployees',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantcoupons',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_coupon_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantcoupons',
            name='merchant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Merchant'),
        ),
        migrations.AddField(
            model_name='merchantcoupons',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Store'),
        ),
        migrations.AddField(
            model_name='merchantcoupons',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantcategory',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='category_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchantaccesskeys',
            name='merchant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='merchants.Merchant'),
        ),
        migrations.AddField(
            model_name='merchantaccesskeys',
            name='store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='merchants.Store'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchant_added_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Addresses'),
        ),
        migrations.AddField(
            model_name='merchant',
            name='merchant_head',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
