# Generated by Django 2.2.6 on 2019-10-26 03:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_auto_20191024_0335'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='store_location',
            field=django.contrib.gis.db.models.fields.PointField(default='', srid=4326),
            preserve_default=False,
        ),
    ]
