# Generated by Django 2.2.6 on 2019-10-24 03:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merchants', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('offer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('tax_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('state_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='In Rupee')),
                ('central_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='In Rupee')),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('pickup_otp', models.IntegerField()),
                ('mobile_no', models.IntegerField(db_index=True)),
                ('payment_type', models.IntegerField(choices=[(1, 'Cash'), (2, 'Card'), (3, 'Net Banking'), (4, 'UPI'), (5, 'Other')], default=2)),
                ('delivery_type', models.IntegerField(choices=[(1, 'Pickup'), (2, 'Home Devlivery'), (3, 'Store')], default=3)),
                ('order_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Placed'), (3, 'Paid'), (4, 'In Transaction'), (5, 'Waiting'), (6, 'Delivered'), (7, 'Returned'), (8, 'Declined'), (9, 'Feedback Accepted')], default=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('currency', models.IntegerField(choices=[(1, 'INR'), (2, 'OTHER')], default=1)),
                ('txn_gateway_id', models.CharField(max_length=70)),
                ('txn_bank_id', models.CharField(max_length=255)),
                ('txn_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failed')], default=1)),
                ('txn_gateway_name', models.CharField(max_length=20)),
                ('txn_bank', models.TextField()),
                ('txn_mode', models.CharField(max_length=20)),
                ('txn_date', models.DateTimeField()),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.Customer')),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Merchant')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Orders')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='merchants.Store')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
