# Generated by Django 2.2.6 on 2019-10-24 03:35

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('product_name', models.CharField(db_index=True, max_length=255)),
                ('product_desc', models.TextField()),
                ('manufacturer', models.CharField(db_index=True, max_length=255)),
                ('manufacturer_details', models.TextField()),
                ('metric_system', models.IntegerField(choices=[(0, 'KG'), (1, 'Metre'), (2, 'Litre'), (3, 'Dozen'), (4, 'Quantity'), (5, 'Unknown')], default=4)),
                ('product_slug', models.CharField(max_length=255)),
                ('other', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='ProductAttribute',
            fields=[
                ('attribute_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('attribute_name', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Attribute',
                'verbose_name_plural': 'Product Attributes',
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeValue',
            fields=[
                ('attr_value_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Attribute Value',
                'verbose_name_plural': 'Product Attribute Values',
            },
        ),
        migrations.CreateModel(
            name='ProductCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=255)),
                ('sub_category_name', models.CharField(max_length=255)),
                ('category_slug', models.SlugField(max_length=255, unique=True)),
                ('other', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Produc Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Tax Exclusive')),
                ('discounted_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Tax Exclusive')),
                ('sale_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='Tax Inclusive')),
                ('sale_from', models.DateTimeField(blank=True, null=True, verbose_name='Sale start')),
                ('sale_to', models.DateTimeField(blank=True, null=True, verbose_name='Sale end')),
                ('is_tax_inclusive', models.BooleanField(default=True)),
                ('state_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='In percent')),
                ('central_gst', models.DecimalField(decimal_places=2, default=0.0, max_digits=8, verbose_name='In Percent')),
                ('merchant_product_id', models.CharField(max_length=255, null=True)),
                ('quantity', models.IntegerField(default=0)),
                ('other_details', models.TextField(help_text='Other Product Related Details')),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Details',
                'verbose_name_plural': 'Products Details',
            },
        ),
        migrations.CreateModel(
            name='ProductImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.IntegerField(verbose_name='In KB')),
                ('format', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='products/images/')),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Category',
                'verbose_name_plural': 'Product Categories',
            },
        ),
        migrations.CreateModel(
            name='ProductOffer',
            fields=[
                ('offer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('discount_type', models.IntegerField(choices=[(0, 'Percent'), (1, 'Flat')], db_index=True, default=0)),
                ('discount', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('min_quantity', models.IntegerField(verbose_name='Minimum Product Quantity to apply Offer')),
                ('coupon_code', models.CharField(db_index=True, max_length=50, unique=True)),
                ('available_after', models.DateTimeField(db_index=True)),
                ('expire_before', models.DateTimeField(db_index=True)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Product Offers',
                'verbose_name_plural': 'Products Offers',
            },
        ),
    ]
